export const CHANGE_TOP_BANNERS = 'CHANGE_TOP_BANNERS'
export const CHANGE_HOT_RECOMMEND = 'CHANGE_HOT_RECOMMEND'
export const CHANGE_TOP_ALBUM = 'CHANGE_TOP_ALBUM'

export const CHANGE_UP_RANKING = 'CHANGE_UP_RANKING'
export const CHANGE_NEW_RANKING = 'CHANGE_NEW_RANKING'
export const CHANGE_ORIGIN_RANKING = 'CHANGE_ORIGIN_RANKING'

export const CHANGE_TOP_ARTISTS = 'CHANGE_TOP_ARTISTS'
export const CHANGE_DJ_PAYGIFT = 'CHANGE_DJ_PAYGIFT'
